const vk = @import("vk");

const debug_apis: []const vk.ApiInfo = &.{.{ .instance_commands = .{
    .createDebugUtilsMessengerEXT = true,
    .destroyDebugUtilsMessengerEXT = true,
} }};

const apis: []const vk.ApiInfo = &.{
    .{
        .base_commands = .{
            .createInstance = true,
            .enumerateInstanceExtensionProperties = true,
            .enumerateInstanceLayerProperties = true,
            .getInstanceProcAddr = true,
        },
        .instance_commands = .{
            .createDevice = true,
            .destroyInstance = true,
            .destroySurfaceKHR = true,
            .enumerateDeviceExtensionProperties = true,
            .enumeratePhysicalDevices = true,
            .getDeviceProcAddr = true,
            .getPhysicalDeviceFeatures = true,
            .getPhysicalDeviceFormatProperties = true,
            .getPhysicalDeviceMemoryProperties = true,
            .getPhysicalDeviceProperties = true,
            .getPhysicalDeviceProperties2 = true,
            .getPhysicalDeviceQueueFamilyProperties = true,
            .getPhysicalDeviceSurfaceCapabilitiesKHR = true,
            .getPhysicalDeviceSurfaceFormatsKHR = true,
            .getPhysicalDeviceSurfacePresentModesKHR = true,
            .getPhysicalDeviceSurfaceSupportKHR = true,
        },
        .device_commands = .{
            .acquireNextImageKHR = true,
            .allocateCommandBuffers = true,
            .allocateDescriptorSets = true,
            .allocateMemory = true,
            .beginCommandBuffer = true,
            .bindBufferMemory = true,
            .bindImageMemory = true,
            .cmdBeginRendering = true,
            .cmdBindDescriptorSets = true,
            .cmdBindPipeline = true,
            .cmdBindVertexBuffers = true,
            .cmdClearAttachments = true,
            .cmdClearColorImage = true,
            .cmdClearDepthStencilImage = true,
            .cmdCopyBuffer2 = true,
            .cmdCopyImage2 = true,
            .cmdDispatch = true,
            .cmdDraw = true,
            .cmdEndRendering = true,
            .cmdExecuteCommands = true,
            .cmdPipelineBarrier2 = true,
            .cmdPushConstants = true,
            .cmdSetPrimitiveTopology = true,
            .cmdSetScissor = true,
            .cmdSetViewport = true,
            .createBuffer = true,
            .createCommandPool = true,
            .createComputePipelines = true,
            .createDescriptorPool = true,
            .createDescriptorSetLayout = true,
            .createFence = true,
            .createGraphicsPipelines = true,
            .createImage = true,
            .createImageView = true,
            .createPipelineLayout = true,
            .createSampler = true,
            .createSemaphore = true,
            .createShaderModule = true,
            .createSwapchainKHR = true,
            .destroyBuffer = true,
            .destroyCommandPool = true,
            .destroyDescriptorPool = true,
            .destroyDescriptorSetLayout = true,
            .destroyDevice = true,
            .destroyFence = true,
            .destroyImage = true,
            .destroyImageView = true,
            .destroyPipeline = true,
            .destroyPipelineLayout = true,
            .destroySampler = true,
            .destroySemaphore = true,
            .destroyShaderModule = true,
            .destroySwapchainKHR = true,
            .deviceWaitIdle = true,
            .endCommandBuffer = true,
            .freeCommandBuffers = true,
            .freeDescriptorSets = true,
            .freeMemory = true,
            .getBufferMemoryRequirements = true,
            .getDeviceQueue = true,
            .getImageMemoryRequirements = true,
            .getSwapchainImagesKHR = true,
            .mapMemory = true,
            .queuePresentKHR = true,
            .queueSubmit = true,
            .queueWaitIdle = true,
            .resetCommandBuffer = true,
            .resetFences = true,
            .unmapMemory = true,
            .updateDescriptorSets = true,
            .waitForFences = true,
        },
    },
};

pub const Base = vk.BaseWrapper(apis);
pub const DebugMsg = vk.InstanceWrapper(debug_apis);
pub const Instance = vk.InstanceWrapper(apis);
pub const Device = vk.DeviceWrapper(apis);
